from pathlib import Path

from projtree.generator import generate_markdown_tree


def test_single_file(tmp_path: Path):
    (tmp_path / "README.md").write_text("", encoding="utf-8")

    result = generate_markdown_tree(tmp_path)

    expected = (
        "# Project Structure\n\n"
        "_Generated by projtree_\n\n"
        "```\n"
        ".\n"
        "└── README.md\n"
        "```\n"
    )

    assert result == expected


def test_nested_directories(tmp_path: Path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("", encoding="utf-8")
    (tmp_path / "src" / "utils.py").write_text("", encoding="utf-8")

    result = generate_markdown_tree(tmp_path)

    expected = (
        "# Project Structure\n\n"
        "_Generated by projtree_\n\n"
        "```\n"
        ".\n"
        "└── src\n"
        "    ├── main.py\n"
        "    └── utils.py\n"
        "```\n"
    )

    assert result == expected


def test_directories_before_files(tmp_path: Path):
    (tmp_path / "b_file.txt").write_text("", encoding="utf-8")
    (tmp_path / "a_dir").mkdir()
    (tmp_path / "a_dir" / "file.txt").write_text("", encoding="utf-8")

    result = generate_markdown_tree(tmp_path)

    expected = (
        "# Project Structure\n\n"
        "_Generated by projtree_\n\n"
        "```\n"
        ".\n"
        "├── a_dir\n"
        "│   └── file.txt\n"
        "└── b_file.txt\n"
        "```\n"
    )

    assert result == expected


def test_ignored_paths_are_omitted(tmp_path: Path):
    (tmp_path / ".git").mkdir()
    (tmp_path / ".git" / "config").write_text("", encoding="utf-8")
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("", encoding="utf-8")

    result = generate_markdown_tree(tmp_path, ignore={".git"})

    expected = (
        "# Project Structure\n\n"
        "_Generated by projtree_\n\n"
        "```\n"
        ".\n"
        "└── src\n"
        "    └── main.py\n"
        "```\n"
    )

    assert result == expected


def test_output_is_deterministic(tmp_path: Path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "b.py").write_text("", encoding="utf-8")
    (tmp_path / "src" / "a.py").write_text("", encoding="utf-8")

    first = generate_markdown_tree(tmp_path)
    second = generate_markdown_tree(tmp_path)

    assert first == second


def test_unicode_characters_are_preserved(tmp_path: Path):
    (tmp_path / "café").mkdir()
    (tmp_path / "café" / "naïve.py").write_text("", encoding="utf-8")

    result = generate_markdown_tree(tmp_path)

    expected = (
        "# Project Structure\n\n"
        "_Generated by projtree_\n\n"
        "```\n"
        ".\n"
        "└── café\n"
        "    └── naïve.py\n"
        "```\n"
    )

    assert result == expected
