name: Run tests

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["Run linter"]
    types:
      - completed

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          persist-credentials: false
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: SetUp python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install ."[dev]"

      - name: Run Tests
        run: python -m pytest -v
